name: fitphone
description: Gym app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  screentheme: ^0.0.2
  percent_indicator: ^2.1.1+1
  shared_preferences: ^0.5.3+4
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.6
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+4
  image_picker: ^0.6.1+4
  fcharts: ^0.0.11
  cached_network_image: ^1.1.1
  toast: ^0.1.5
  intl: ^0.15.2
  rounded_modal: ^1.0.1
  flutter_statusbarcolor: ^0.2.2
  image_cropper: ^1.0.2
  youtube_player_flutter: ^4.1.0
  random_string: ^1.1.0
  provider: ^3.1.0
  animated_text_kit: ^1.3.1
  flutter_fadein: ^1.1.1
  flutter_xlider: ^2.5.2
  flutter_vector_icons: ^0.2.1
  flutter_spinkit: ^4.0.0
  page_transition: ^1.1.4
  charts_flutter: ^0.8.1
  date_util: ^0.1.4
  transparent_image: ^1.0.0
  bubble_tab_indicator: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/logo.png
  - assets/logo_white.png
  - assets/placeholder_face.png
  - assets/weight.png
  - assets/workout.png
  - assets/strenght.png
  - assets/activity_image.png
  - assets/goal_image.png
  - assets/welcome_image.png
  - assets/weight_image.png
  - assets/unit_image.png
  - assets/diet_image.png
  - assets/summary_image.png
  - assets/workout_image.png
  - assets/nutrition_image.png
  - assets/dump_image.png
  - assets/happy.png
  - assets/neutral.png
  - assets/sad.png
  - assets/program.png
  - assets/folder.png
  - assets/trophy_hand.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
