/// Flutter icons NavigationIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationIcons
///      fonts:
///       - asset: fonts/NavigationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationIcons {
  NavigationIcons._();

  static const _kFontFam = 'NavigationIcons';

  static const IconData settings = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData dumbbell = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData line_chart = const IconData(0xe80b, fontFamily: _kFontFam);
}
