/// Flutter icons NutritionIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NutritionIcons
///      fonts:
///       - asset: fonts/NutritionIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class NutritionIcons {
  NutritionIcons._();

  static const _kFontFam = 'NutritionIcons';

  static const IconData cauliflower = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData wheat_grains = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData broccoli_vegetable_silhouette = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bread_silhouette_side_view = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData resize_small = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calories = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData papaya = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData meat = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cereal = const IconData(0xe809, fontFamily: _kFontFam);
}
