/// Flutter icons SystemIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SystemIcon
///      fonts:
///       - asset: fonts/SystemIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SystemIcon {
  SystemIcon._();

  static const _kFontFam = 'SystemIcon';

  static const IconData shield = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData like = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData new_email_back_closed_envelope_symbol = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData scale = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData paint_brushes = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe814, fontFamily: _kFontFam);
}
